sudo: false
language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - hhvm
  - hhvm-nightly
matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
before_script:
  - composer install
  - mkdir -p build/logs
script: ./vendor/bin/atoum
after_script:
  - php vendor/bin/coveralls -v
