sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
matrix:
  allow_failures:
    - 7.0
    - php: hhvm
    - php: hhvm-nightly
before_script:
  - composer install
  - mkdir -p build/logs
script: ./vendor/bin/atoum
after_script:
  - ./vendor/bin/coveralls -v
  - ./vendor/bin/test-reporter
addons:
  code_climate:
    repo_token: 2cc18d63966954312cb7ccd1edff08f5aa638cb3b361c6f671ef3a4188eced81
